[package]
name = "websocket-test"
version = "0.1.0"
authors = ["Stephen Cirner <scirner@getcrossbeam.com>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
